# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.idle1.frame matches 41.. run scoreboard players set @s aj.idle1.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.idle1.frame
execute at @s run function animated_java:thebrokenend/animations/idle1/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.idle1.frame 1