# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add aj.thebrokenend.animation.idle1.playing
scoreboard players set @s aj.idle1.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:thebrokenend/animations/idle1/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only