# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.head.uuid
function animated_java:tbs_player/zzz/execute with storage aj:temp