# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data merge entity @s {item:{id:"minecraft:white_dye",count:1,components:{item_model:"minecraft:air"}},transformation:{translation: [0.0f, 0.5f, 0.0f], right_rotation: [0.0f, 0.0f, 0.0f, 1.0f], scale: [1.0f, 1.0f, 1.0f], left_rotation: [0.0f, 1.0f, 0.0f, 0.0f]},teleport_duration:1}