# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.pose.frame dummy
scoreboard objectives add aj.pose1.frame dummy
scoreboard objectives add aj.pose2.frame dummy