# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.run.frame matches 11.. run scoreboard players set @s aj.run.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.run.frame
execute at @s run function animated_java:thebrokenend/animations/run/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.run.frame 1