# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.tbs_player.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'tbs_player', 'function_path': 'animated_java:tbs_player/variants/null/apply'}
execute on passengers if entity @s[tag=aj.tbs_player.bone.left_leg] run function animated_java:tbs_player/variants/null/zzz/0
execute on passengers if entity @s[tag=aj.tbs_player.bone.right_leg] run function animated_java:tbs_player/variants/null/zzz/1
execute on passengers if entity @s[tag=aj.tbs_player.bone.right_arm] run function animated_java:tbs_player/variants/null/zzz/2
execute on passengers if entity @s[tag=aj.tbs_player.bone.left_arm] run function animated_java:tbs_player/variants/null/zzz/3
execute on passengers if entity @s[tag=aj.tbs_player.bone.head1] run function animated_java:tbs_player/variants/null/zzz/4
execute on passengers if entity @s[tag=aj.tbs_player.bone.body] run function animated_java:tbs_player/variants/null/zzz/5