# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone10] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone22] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone22 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone11] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone25] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone25 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone26] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone26 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone27] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone27 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone28] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone28 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone23] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone23 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone24] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone24 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone9] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone18] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone18 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone17] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone17 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone19] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone19 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.thebrokenend.node.bone16] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone16 set from storage aj:uuid main.out