# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.walk.frame matches 49.. run scoreboard players set @s aj.walk.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.walk.frame
execute at @s run function animated_java:tbs_player/animations/walk/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.walk.frame 1