# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:thebrokenend/animations/idle1/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.idle1.frame 1