# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.thebrokenend.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'thebrokenend', 'function_path': 'animated_java:thebrokenend/animations/pause_all'}
tag @s remove aj.thebrokenend.animation.idle1.playing
tag @s remove aj.thebrokenend.animation.idle2.playing
tag @s remove aj.thebrokenend.animation.walk.playing
tag @s remove aj.thebrokenend.animation.run.playing
tag @s remove aj.thebrokenend.animation.despawn.playing