# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.tbs_thumb.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'tbs_thumb', 'function_path': 'animated_java:tbs_thumb/animations/pause_all'}
tag @s remove aj.tbs_thumb.animation.pose.playing
tag @s remove aj.tbs_thumb.animation.pose1.playing
tag @s remove aj.tbs_thumb.animation.pose2.playing