# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers run function animated_java:tbs_player/remove/zzz/kill_passengers
kill @s