# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.circuit.node.bone5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.circuit.node.bone6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.circuit.node.bone3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.circuit.node.bone2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.circuit.node.bone4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.circuit.node.bone] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone set from storage aj:uuid main.out