# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.chase2.frame matches 4.. run scoreboard players set @s aj.chase2.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.chase2.frame
execute at @s run function animated_java:circuit/animations/chase2/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.chase2.frame 1