# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add aj.circuit.animation.chase2.playing
scoreboard players set @s aj.chase2.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:circuit/animations/chase2/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only