# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.despawn.frame matches 36.. run scoreboard players set @s aj.despawn.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.despawn.frame
execute at @s run function animated_java:thebrokenend/animations/despawn/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.despawn.frame 1