# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tbs_player/animations/angry_curved_idle/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.angry_curved_idle.frame 1