# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.siluet.root] run return 0
function #animated_java:siluet/as_root/pre_tick
execute if entity @s[tag=aj.siluet.animation.idle.playing] run function animated_java:siluet/animations/idle/zzz/on_tick
execute on passengers if entity @s[tag=aj.siluet.data] run function animated_java:siluet/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
function #animated_java:siluet/as_root/post_tick