# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.pose1.frame matches 2.. run scoreboard players set @s aj.pose1.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.pose1.frame
execute at @s run function animated_java:tbs_thumb/animations/pose1/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.pose1.frame 1