# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.pose1.frame $(frame)
execute at @s run function animated_java:tbs_thumb/animations/pose1/zzz/set_frame with storage aj:temp