# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tbs_thumb.root] run return 0
function #animated_java:tbs_thumb/as_root/pre_tick
execute if entity @s[tag=aj.tbs_thumb.animation.pose.playing] run function animated_java:tbs_thumb/animations/pose/zzz/on_tick
execute if entity @s[tag=aj.tbs_thumb.animation.pose1.playing] run function animated_java:tbs_thumb/animations/pose1/zzz/on_tick
execute if entity @s[tag=aj.tbs_thumb.animation.pose2.playing] run function animated_java:tbs_thumb/animations/pose2/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:tbs_thumb/as_root/post_tick