# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:circuit/animations/chase2/zzz/apply_frame {frame: 3}
scoreboard players add @s aj.chase2.frame 1