# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.thebrokenend.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'thebrokenend', 'function_path': 'animated_java:thebrokenend/variants/angry/apply'}
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone10] run function animated_java:thebrokenend/variants/angry/zzz/0
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone6] run function animated_java:thebrokenend/variants/angry/zzz/1
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone5] run function animated_java:thebrokenend/variants/angry/zzz/2
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone4] run function animated_java:thebrokenend/variants/angry/zzz/3
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone8] run function animated_java:thebrokenend/variants/angry/zzz/4
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone7] run function animated_java:thebrokenend/variants/angry/zzz/5
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone3] run function animated_java:thebrokenend/variants/angry/zzz/6
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone22] run function animated_java:thebrokenend/variants/angry/zzz/7
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone11] run function animated_java:thebrokenend/variants/angry/zzz/8
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone25] run function animated_java:thebrokenend/variants/angry/zzz/9
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone26] run function animated_java:thebrokenend/variants/angry/zzz/10
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone27] run function animated_java:thebrokenend/variants/angry/zzz/11
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone28] run function animated_java:thebrokenend/variants/angry/zzz/12
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone] run function animated_java:thebrokenend/variants/angry/zzz/13
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone23] run function animated_java:thebrokenend/variants/angry/zzz/14
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone24] run function animated_java:thebrokenend/variants/angry/zzz/15
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone9] run function animated_java:thebrokenend/variants/angry/zzz/16
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone18] run function animated_java:thebrokenend/variants/angry/zzz/17
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone17] run function animated_java:thebrokenend/variants/angry/zzz/18
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone19] run function animated_java:thebrokenend/variants/angry/zzz/19
execute on passengers if entity @s[tag=aj.thebrokenend.bone.bone16] run function animated_java:thebrokenend/variants/angry/zzz/20