# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.idle2.frame dummy
scoreboard objectives add aj.chase.frame dummy
scoreboard objectives add aj.chase2.frame dummy
scoreboard objectives add aj.new.frame dummy
scoreboard objectives add aj.crouchidle.frame dummy
scoreboard objectives add aj.crouchwalk.frame dummy
scoreboard objectives add aj.peeking.frame dummy