# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function #animated_java:tbs_thumb/as_root/on_remove
execute on passengers run kill @s
kill @s