# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.thebrokenend.root] run return 0
function #animated_java:thebrokenend/as_root/pre_tick
execute if entity @s[tag=aj.thebrokenend.animation.idle1.playing] run function animated_java:thebrokenend/animations/idle1/zzz/on_tick
execute if entity @s[tag=aj.thebrokenend.animation.idle2.playing] run function animated_java:thebrokenend/animations/idle2/zzz/on_tick
execute if entity @s[tag=aj.thebrokenend.animation.walk.playing] run function animated_java:thebrokenend/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.thebrokenend.animation.run.playing] run function animated_java:thebrokenend/animations/run/zzz/on_tick
execute if entity @s[tag=aj.thebrokenend.animation.despawn.playing] run function animated_java:thebrokenend/animations/despawn/zzz/on_tick
execute on passengers if entity @s[tag=aj.thebrokenend.data] run function animated_java:thebrokenend/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
function #animated_java:thebrokenend/as_root/post_tick