# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.circuit.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'circuit', 'function_path': 'animated_java:circuit/animations/pause_all'}
tag @s remove aj.circuit.animation.idle.playing
tag @s remove aj.circuit.animation.idle2.playing
tag @s remove aj.circuit.animation.chase.playing
tag @s remove aj.circuit.animation.chase2.playing
tag @s remove aj.circuit.animation.new.playing
tag @s remove aj.circuit.animation.crouchidle.playing
tag @s remove aj.circuit.animation.crouchwalk.playing
tag @s remove aj.circuit.animation.peeking.playing