# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.crouchidle.frame matches 21.. run scoreboard players set @s aj.crouchidle.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.crouchidle.frame
execute at @s run function animated_java:circuit/animations/crouchidle/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.crouchidle.frame 1