 // Source code is unavailable, and was generated by the Fernflower decompiler.
package net.mcreator.interpritation.procedures;

import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import javax.annotation.Nullable;
import net.mcreator.interpritation.ThebrokenscriptMod;
import net.mcreator.interpritation.init.ThebrokenscriptModBlocks;
import net.mcreator.interpritation.init.ThebrokenscriptModEntities;
import net.mcreator.interpritation.init.ThebrokenscriptModMobEffects;
import net.mcreator.interpritation.init.ThebrokenscriptModParticleTypes;
import net.mcreator.interpritation.network.ThebrokenscriptModVariables.MapVariables;
import net.mcreator.interpritation.procedures.EventEngineProcedure.1;
import net.mcreator.interpritation.procedures.EventEngineProcedure.2;
import net.mcreator.interpritation.procedures.EventEngineProcedure.3;
import net.mcreator.interpritation.procedures.EventEngineProcedure.4;
import net.minecraft.advancements.Advancement;
import net.minecraft.advancements.AdvancementProgress;
import net.minecraft.client.Minecraft;
import net.minecraft.commands.CommandSource;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.arguments.EntityAnchorArgument.Anchor;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.sounds.SoundSource;
import net.minecraft.tags.BlockTags;
import net.minecraft.util.Mth;
import net.minecraft.util.RandomSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.damagesource.DamageTypes;
import net.minecraft.world.effect.MobEffect;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.LightningBolt;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.MobSpawnType;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.ClipContext;
import net.minecraft.world.level.GameRules;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.ClipContext.Fluid;
import net.minecraft.world.level.GameRules.BooleanValue;
import net.minecraft.world.level.Level.ExplosionInteraction;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.Mirror;
import net.minecraft.world.level.block.Rotation;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructurePlaceSettings;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate;
import net.minecraft.world.level.storage.LevelData;
import net.minecraft.world.level.storage.WritableLevelData;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.Vec2;
import net.minecraft.world.phys.Vec3;
import net.minecraftforge.event.TickEvent.Phase;
import net.minecraftforge.event.TickEvent.PlayerTickEvent;
import net.minecraftforge.eventbus.api.Event;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.items.ItemHandlerHelper;
import net.minecraftforge.network.NetworkHooks;
import net.minecraftforge.registries.ForgeRegistries;

@EventBusSubscriber
public class EventEngineProcedure {
   @SubscribeEvent
   public static void onPlayerTick(PlayerTickEvent event) {
      if (event.phase == Phase.END) {
         execute(event, event.player.getActiveEffects(), event.player.m_20185_(), event.player.m_20186_(), event.player.m_20189_(), event.player);
      }

   }

   public static void execute(LevelAccessor world, double x, double y, double z, Entity entity) {
      execute((Event)null, world, x, y, z, entity);
   }

   private static void execute(@Nullable Event event, LevelAccessor world, double x, double y, double z, Entity entity) {
      if (entity != null) {
         boolean found = false;
         double textengine = 0.0D;
         double soundengine = 0.0D;
         double guiengine = 0.0D;
         double eventengine = 0.0D;
         double sx = 0.0D;
         double sy = 0.0D;
         double sz = 0.0D;
         if (!MapVariables.get(world).config_randomevents) {
            if (Math.random() < 3.0E-5D) {
               eventengine = (double)Mth.m_216271_(RandomSource.m_216327_(), 1, 54);
               if (eventengine == 1.0D) {
                  eventengine = 0.0D;
                  ThebrokenscriptMod.queueServerWork(1, () -> {
                     entity.player_damage(new DamageSource(world.m_9598_().m_175515_(Registries.f_268580_).m_246971_(DamageTypes.f_268433_)), 1.0F);
                     entity.player_rotate(Anchor.EYES, new Vec3(x, y, z));
                     ThebrokenscriptMod.queueServerWork(5, () -> {
                        entity.player_damage(new DamageSource(world.m_9598_().m_175515_(Registries.f_268580_).m_246971_(DamageTypes.f_268433_)), 1.0F);
                        entity.player_rotate(Anchor.EYES, new Vec3(x, y + 20.0D, z));
                        ThebrokenscriptMod.queueServerWork(5, () -> {
                           entity.player_damage(new DamageSource(world.m_9598_().m_175515_(Registries.f_268580_).m_246971_(DamageTypes.f_268433_)), 1.0F);
                           entity.player_rotate(Anchor.EYES, new Vec3(x + 20.0D, y, z));
                           ThebrokenscriptMod.queueServerWork(5, () -> {
                              entity.player_damage(new DamageSource(world.m_9598_().m_175515_(Registries.f_268580_).m_246971_(DamageTypes.f_268433_)), 1.0F);
                              entity.player_rotate(Anchor.EYES, new Vec3(x, y, z + 20.0D));
                           });
                        });
                     });
                  });
               }

               if (eventengine == 2.0D) {
                  eventengine = 0.0D;
                  entity.player_damage(new DamageSource(world.m_9598_().m_175515_(Registries.f_268580_).m_246971_(DamageTypes.f_268433_)), 1.0F);
               }

               if (eventengine == 3.0D) {
                  eventengine = 0.0D;
                  ThebrokenscriptMod.queueServerWork(1, () -> {
                     if (world instanceof Level) {
                        Level _level = (Level)world;
                        if (!_level.isClientSide()) {
                           _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("thebrokenscript:randomsong")), SoundSource.NEUTRAL, 555.0F, 1.0F);
                        } else {
                           _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("thebrokenscript:randomsong")), SoundSource.NEUTRAL, 555.0F, 1.0F, false);
                        }
                     }

                     if (world instanceof ServerLevel) {
                        ServerLevel _levelx = (ServerLevel)world;
                        _levelx.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _levelx, 4, "", Component.literal(""), _levelx.getServer(), (Entity)null)).m_81324_(), "time set midnight");
                     }

                     LivingEntity _entity;
                     if (entity instanceof LivingEntity) {
                        _entity = (LivingEntity)entity;
                        if (!_entity.getActiveEffects().isClientSide()) {
                           _entity.addEffect(new MobEffectInstance(MobEffects.f_19610_, 320, 1));
                        }
                     }

                     if (entity instanceof LivingEntity) {
                        _entity = (LivingEntity)entity;
                        if (!_entity.getActiveEffects().isClientSide()) {
                           _entity.addEffect(new MobEffectInstance(MobEffects.f_19597_, 320, 1));
                        }
                     }

                     if (entity instanceof LivingEntity) {
                        _entity = (LivingEntity)entity;
                        if (!_entity.getActiveEffects().isClientSide()) {
                           _entity.addEffect(new MobEffectInstance(MobEffects.f_19591_, 320, 1));
                        }
                     }

                     ThebrokenscriptMod.queueServerWork(320, () -> {
                        if (Math.random() < 0.5D && world instanceof ServerLevel) {
                           ServerLevel _level = (ServerLevel)world;
                           Entity entityToSpawn = ((EntityType)ThebrokenscriptModEntities.STRIKE.get()).create(_level, BlockPos.NewBlock(x, y, z), MobSpawnType.MOB_SUMMONED);
                           if (entityToSpawn != null) {
                              entityToSpawn.setYRot(world.m_213780_().m_188501_() * 360.0F);
                           }
                        }

                     });
                  });
               }

               if (eventengine == 4.0D) {
                  eventengine = 0.0D;
                  entity.m_20254_(3);
               }

               ServerLevel _serverworld;
               if (eventengine == 5.0D) {
                  eventengine = 0.0D;
                  LightningBolt entityToSpawn;
                  if (Math.random() < 0.5D) {
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        entityToSpawn = (LightningBolt)EntityType.f_20465_.m_20615_(_serverworld);
                        entityToSpawn.m_20219_(Vec3.m_82539_(BlockPos.NewBlock(x + (double)Mth.m_216271_(RandomSource.m_216327_(), 1, 10), y, z + (double)Mth.m_216271_(RandomSource.m_216327_(), 1, 10))));
                        _serverworld.m_7967_(entityToSpawn);
                     }
                  } else if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     entityToSpawn = (LightningBolt)EntityType.f_20465_.m_20615_(_serverworld);
                     entityToSpawn.m_20219_(Vec3.m_82539_(BlockPos.NewBlock(x - (double)Mth.m_216271_(RandomSource.m_216327_(), 1, 10), y, z - (double)Mth.m_216271_(RandomSource.m_216327_(), 1, 10))));
                     _serverworld.m_7967_(entityToSpawn);
                  }
               }

               Level _level;
               if (eventengine == 6.0D) {
                  eventengine = 0.0D;
                  if (world instanceof Level) {
                     _level = (Level)world;
                     if (!_level.isClientSide()) {
                        _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("block.grass.break")), SoundSource.NEUTRAL, 1.0F, 1.0F);
                     } else {
                        _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("block.grass.break")), SoundSource.NEUTRAL, 1.0F, 1.0F, false);
                     }
                  }

                  ThebrokenscriptMod.queueServerWork(20, () -> {
                     if (world instanceof Level) {
                        Level _level = (Level)world;
                        if (!_level.isClientSide()) {
                           _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("block.grass.break")), SoundSource.NEUTRAL, 1.0F, 1.0F);
                        } else {
                           _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("block.grass.break")), SoundSource.NEUTRAL, 1.0F, 1.0F, false);
                        }
                     }

                     ThebrokenscriptMod.queueServerWork(20, () -> {
                        if (world instanceof Level) {
                           Level _level = (Level)world;
                           if (!_level.isClientSide()) {
                              _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("block.grass.break")), SoundSource.NEUTRAL, 1.0F, 1.0F);
                           } else {
                              _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("block.grass.break")), SoundSource.NEUTRAL, 1.0F, 1.0F, false);
                           }
                        }

                        ThebrokenscriptMod.queueServerWork(20, () -> {
                           if (world instanceof Level) {
                              Level _level = (Level)world;
                              if (!_level.isClientSide()) {
                                 _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("block.grass.break")), SoundSource.NEUTRAL, 1.0F, 1.0F);
                              } else {
                                 _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("block.grass.break")), SoundSource.NEUTRAL, 1.0F, 1.0F, false);
                              }
                           }

                        });
                     });
                  });
               }

               if (eventengine == 7.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "time set night");
                  }

                  if (Math.random() < 0.5D) {
                     if (world instanceof Level) {
                        _level = (Level)world;
                        if (!_level.isClientSide()) {
                           _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("ambient.cave")), SoundSource.NEUTRAL, 1.0F, 0.0F);
                        } else {
                           _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("ambient.cave")), SoundSource.NEUTRAL, 1.0F, 0.0F, false);
                        }
                     }

                     if (world instanceof Level) {
                        _level = (Level)world;
                        if (!_level.isClientSide()) {
                           _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("thebrokenscript:heartbeat")), SoundSource.NEUTRAL, 1.0F, 1.0F);
                        } else {
                           _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("thebrokenscript:heartbeat")), SoundSource.NEUTRAL, 1.0F, 1.0F, false);
                        }
                     }
                  }
               }

               Player _player;
               if (eventengine == 8.0D) {
                  eventengine = 0.0D;
                  if (entity instanceof Player) {
                     _player = (Player)entity;
                     _player.m_36324_().m_38705_(Mth.m_216271_(RandomSource.m_216327_(), 1, 10));
                  }
               }

               if (eventengine == 9.0D) {
                  eventengine = 0.0D;
                  if (entity instanceof Player) {
                     _player = (Player)entity;
                     _player.m_6915_();
                  }
               }

               BlockPos _bp;
               ServerPlayer _player;
               if (eventengine == 10.0D) {
                  eventengine = 0.0D;
                  guiengine = (double)Mth.m_216271_(RandomSource.m_216327_(), 1, 3);
                  if (guiengine == 1.0D) {
                     eventengine = 0.0D;
                     if (entity instanceof ServerPlayer) {
                        _player = (ServerPlayer)entity;
                        _bp = BlockPos.NewBlock(x, y, z);
                        NetworkHooks.openScreen(_player, new 1(_bp), _bp);
                     }
                  }

                  if (guiengine == 2.0D) {
                     eventengine = 0.0D;
                     if (entity instanceof ServerPlayer) {
                        _player = (ServerPlayer)entity;
                        _bp = BlockPos.NewBlock(x, y, z);
                        NetworkHooks.openScreen(_player, new 2(_bp), _bp);
                     }
                  }

                  if (guiengine == 3.0D) {
                     eventengine = 0.0D;
                     if (entity instanceof ServerPlayer) {
                        _player = (ServerPlayer)entity;
                        _bp = BlockPos.NewBlock(x, y, z);
                        NetworkHooks.openScreen(_player, new 3(_bp), _bp);
                     }
                  }
               }

               if (eventengine == 11.0D) {
                  eventengine = 0.0D;
                  textengine = (double)Mth.m_216271_(RandomSource.m_216327_(), 1, 13);
                  if (textengine == 1.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a \"I see you.\"");
                     }
                  }

                  if (textengine == 2.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a \"Can you see me?\"");
                     }
                  }

                  if (textengine == 3.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a \"It was your fault.\"");
                     }
                  }

                  if (textengine == 4.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a \"Help us.\"");
                     }
                  }

                  if (textengine == 5.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a \"I am right behind you.\"");
                     }
                  }

                  if (textengine == 6.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a {\"text\":\"I am right behind you.\",\"color\":\"dark_red\"}");
                     }
                  }

                  if (textengine == 7.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a \"null\"");
                     }
                  }

                  if (textengine == 8.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a \"null.err\"");
                     }
                  }

                  if (textengine == 9.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a \"000\"");
                     }
                  }

                  if (textengine == 10.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a {\"text\":\"AAAAAAAAA\",\"obfuscated\":true,\"color\":\"#FFFFFF\"}");
                     }
                  }

                  if (textengine == 11.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a {\"text\":\"Null joined the game\",\"color\":\"yellow\"}");
                     }
                  }

                  if (textengine == 12.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a {\"text\":\"Null left the game\",\"color\":\"yellow\"}");
                     }
                  }

                  if (textengine == 13.0D) {
                     textengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "tellraw @a {\"text\":\"joined the game\",\"color\":\"yellow\"}");
                     }
                  }
               }

               if (eventengine == 12.0D) {
                  eventengine = 0.0D;
                  soundengine = (double)Mth.m_216271_(RandomSource.m_216327_(), 1, 4);
                  if (soundengine == 1.0D) {
                     soundengine = 0.0D;
                     if (world instanceof Level) {
                        _level = (Level)world;
                        if (!_level.isClientSide()) {
                           _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("ambient.cave")), SoundSource.NEUTRAL, 555.0F, (float)Mth.m_216271_(RandomSource.m_216327_(), 0, 1));
                        } else {
                           _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("ambient.cave")), SoundSource.NEUTRAL, 555.0F, (float)Mth.m_216271_(RandomSource.m_216327_(), 0, 1), false);
                        }
                     }
                  }

                  if (soundengine == 2.0D) {
                     soundengine = 0.0D;
                     if (world instanceof Level) {
                        _level = (Level)world;
                        if (!_level.isClientSide()) {
                           _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("music_disc.13")), SoundSource.NEUTRAL, 555.0F, (float)Mth.m_216271_(RandomSource.m_216327_(), 0, 1));
                        } else {
                           _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("music_disc.13")), SoundSource.NEUTRAL, 555.0F, (float)Mth.m_216271_(RandomSource.m_216327_(), 0, 1), false);
                        }
                     }
                  }

                  if (soundengine == 3.0D) {
                     soundengine = 0.0D;
                     if (world instanceof Level) {
                        _level = (Level)world;
                        if (!_level.isClientSide()) {
                           _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("music_disc.11")), SoundSource.NEUTRAL, 555.0F, (float)Mth.m_216271_(RandomSource.m_216327_(), 0, 1));
                        } else {
                           _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("music_disc.11")), SoundSource.NEUTRAL, 555.0F, (float)Mth.m_216271_(RandomSource.m_216327_(), 0, 1), false);
                        }
                     }
                  }

                  if (soundengine == 4.0D) {
                     soundengine = 0.0D;
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "stopsound @a");
                     }
                  }
               }

               AdvancementProgress _ap;
               Iterator var27;
               String criteria;
               Advancement _adv;
               if (eventengine == 13.0D) {
                  eventengine = 0.0D;
                  if (entity instanceof ServerPlayer) {
                     _player = (ServerPlayer)entity;
                     _adv = _player.f_8924_.m_129889_().m_136041_(new ResourceLocation("thebrokenscript:nullnullnull"));
                     _ap = _player.m_8960_().m_135996_(_adv);
                     if (!_ap.m_8193_()) {
                        var27 = _ap.m_8219_().iterator();

                        while(var27.hasNext()) {
                           criteria = (String)var27.next();
                           _player.m_8960_().m_135988_(_adv, criteria);
                        }
                     }
                  }
               }

               if (eventengine == 14.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "give @p written_book[written_book_content={pages:[\"{\\\"text\\\":\\\"null.err.object.err.null.object.alone.3.not.behind.entitytype:player.receiveddata.invalid.reboot.failed.reset.playerdata:00F9219492D94210F812\\\",\\\"color\\\":\\\"black\\\"}\"],title:\"null\",author:null}]");
                  }
               }

               if (eventengine == 15.0D) {
                  eventengine = 0.0D;
               }

               if (eventengine == 16.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "title @a title {\"text\":\"null null null null null null null null\",\"color\":\"#FFFFFF\"}");
                  }
               }

               if (eventengine == 17.0D) {
                  eventengine = 0.0D;
                  world.m_7731_(BlockPos.NewBlock(x, y + (double)Mth.m_216271_(RandomSource.m_216327_(), 50, 60), z), Blocks.f_50752_.m_49966_(), 3);
               }

               if (eventengine == 18.0D) {
                  eventengine = 0.0D;
                  world.m_7731_(BlockPos.NewBlock(x, y + (double)Mth.m_216271_(RandomSource.m_216327_(), 50, 60), z), Blocks.f_49990_.m_49966_(), 3);
               }

               if (eventengine == 19.0D) {
                  eventengine = 0.0D;
                  if (Math.random() < 0.7D) {
                     if (world instanceof Level) {
                        _level = (Level)world;
                        if (!_level.isClientSide()) {
                           _level.m_254849_((Entity)null, x + (double)Mth.m_216271_(RandomSource.m_216327_(), 50, 60), y, z + (double)Mth.m_216271_(RandomSource.m_216327_(), 50, 60), 4.0F, ExplosionInteraction.TNT);
                        }
                     }
                  } else if (world instanceof Level) {
                     _level = (Level)world;
                     if (!_level.isClientSide()) {
                        _level.m_254849_((Entity)null, x - (double)Mth.m_216271_(RandomSource.m_216327_(), 50, 60), y, z - (double)Mth.m_216271_(RandomSource.m_216327_(), 50, 60), 4.0F, ExplosionInteraction.TNT);
                     }
                  }
               }

               if (eventengine == 20.0D) {
                  eventengine = 0.0D;
                  if (Math.random() < 0.7D) {
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "time set midnight");
                     }
                  } else if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "time set day");
                  }
               }

               Entity entityToSpawn;
               if (eventengine == 21.0D) {
                  eventengine = 0.0D;
                  if (Math.random() < 0.5D) {
                     if (world instanceof ServerLevel) {
                        _serverworld = (ServerLevel)world;
                        entityToSpawn = ((EntityType)ThebrokenscriptModEntities.NULL_SCARE.get()).create(_serverworld, BlockPos.NewBlock(x + (double)Mth.m_216271_(RandomSource.m_216327_(), 0, 5), y + (double)Mth.m_216271_(RandomSource.m_216327_(), 0, 5), z + (double)Mth.m_216271_(RandomSource.m_216327_(), 0, 5)), MobSpawnType.MOB_SUMMONED);
                        if (entityToSpawn != null) {
                           entityToSpawn.setYRot(world.m_213780_().m_188501_() * 360.0F);
                        }
                     }
                  } else if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     entityToSpawn = ((EntityType)ThebrokenscriptModEntities.NULL_SCARE.get()).create(_serverworld, BlockPos.NewBlock(x - (double)Mth.m_216271_(RandomSource.m_216327_(), 0, 5), y + (double)Mth.m_216271_(RandomSource.m_216327_(), 0, 5), z - (double)Mth.m_216271_(RandomSource.m_216327_(), 0, 5)), MobSpawnType.MOB_SUMMONED);
                     if (entityToSpawn != null) {
                        entityToSpawn.setYRot(world.m_213780_().m_188501_() * 360.0F);
                     }
                  }
               }

               if (eventengine == 21.0D) {
                  eventengine = 0.0D;
                  if (Math.random() < 0.5D) {
                     if (entity instanceof Player) {
                        _player = (Player)entity;
                        _player.m_6756_(-Mth.m_216271_(RandomSource.m_216327_(), 1, 10));
                     }
                  } else if (entity instanceof Player) {
                     _player = (Player)entity;
                     _player.m_6756_(Mth.m_216271_(RandomSource.m_216327_(), 1, 10));
                  }
               }

               if (eventengine == 22.0D) {
                  eventengine = 0.0D;
                  if (entity instanceof Player) {
                     _player = (Player)entity;
                     ItemStack _setstack = (new ItemStack(Items.f_42710_)).m_41777_();
                     _setstack.m_41764_(1);
                     ItemHandlerHelper.giveItemToPlayer(_player, _setstack);
                  }
               }

               if (eventengine == 23.0D) {
                  eventengine = 0.0D;
                  entity.setYRot(5.0F);
                  entity.m_146926_(0.0F);
                  entity.m_5618_(entity.m_146908_());
                  entity.m_5616_(entity.m_146908_());
                  entity.f_19859_ = entity.m_146908_();
                  entity.f_19860_ = entity.m_146909_();
                  if (entity instanceof LivingEntity) {
                     LivingEntity _entity = (LivingEntity)entity;
                     _entity.f_20884_ = _entity.m_146908_();
                     _entity.f_20886_ = _entity.m_146908_();
                  }
               }

               if (eventengine == 24.0D) {
                  eventengine = 0.0D;
                  world.m_7731_(BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), ((Block)ThebrokenscriptModBlocks.ALL_DEAD.get()).m_49966_(), 3);
               }

               if (eventengine == 25.0D) {
                  eventengine = 0.0D;
                  world.m_7731_(BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), Blocks.f_50174_.m_49966_(), 3);
               }

               if (eventengine == 26.0D) {
                  eventengine = 0.0D;
                  world.m_7731_(BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), Blocks.f_50095_.m_49966_(), 3);
               }

               if (eventengine == 27.0D) {
                  eventengine = 0.0D;
                  world.m_7731_(BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), Blocks.f_49990_.m_49966_(), 3);
                  if (world instanceof Level) {
                     _level = (Level)world;
                     _level.m_46672_(BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), _level.m_8055_(BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ)).m_60734_());
                  }
               }

               if (eventengine == 32.0D) {
                  eventengine = 0.0D;
                  world.m_7731_(BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), ((Block)ThebrokenscriptModBlocks.HELLO.get()).m_49966_(), 3);
               }

               if (eventengine == 41.0D) {
                  eventengine = 0.0D;
                  world.m_7731_(BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), Blocks.f_50134_.m_49966_(), 3);
               }

               if (eventengine == 33.0D) {
                  eventengine = 0.0D;
                  if (world.m_6443_(Player.class, AABB.m_165882_(new Vec3(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), 50.0D, 50.0D, 50.0D), (e) -> {
                     return true;
                  }).isEmpty()) {
                     world.m_7731_(BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), ((Block)ThebrokenscriptModBlocks.EMPTY.get()).m_49966_(), 3);
                  }
               }

               if (eventengine == 27.0D) {
                  eventengine = 0.0D;
                  LevelData var44 = world.m_6106_();
                  if (var44 instanceof WritableLevelData) {
                     WritableLevelData _levelData = (WritableLevelData)var44;
                     _levelData.m_7250_(BlockPos.NewBlock(x, y, z), 0.0F);
                  }
               }

               if (eventengine == 28.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     _serverworld.m_8615_((long)Mth.m_216271_(RandomSource.m_216327_(), 1, 10000));
                  }
               }

               if (eventengine == 29.0D) {
                  eventengine = 0.0D;
                  entity.m_5997_(1.0D, 1.0D, 1.0D);
               }

               if (eventengine == 30.0D) {
                  eventengine = 0.0D;
                  world.m_7106_((SimpleParticleType)ThebrokenscriptModParticleTypes.NULL_PARTICLE.get(), x, y, z, 0.0D, 1.0D, 0.0D);
               }

               if (eventengine == 31.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     entityToSpawn = ((EntityType)ThebrokenscriptModEntities.JFRAME_5ENTITY.get()).create(_serverworld, BlockPos.NewBlock(x, y, z), MobSpawnType.MOB_SUMMONED);
                     if (entityToSpawn != null) {
                        entityToSpawn.setYRot(world.m_213780_().m_188501_() * 360.0F);
                     }
                  }
               }

               if (eventengine == 34.0D) {
                  eventengine = 0.0D;
                  if (entity instanceof ServerPlayer) {
                     _player = (ServerPlayer)entity;
                     _bp = BlockPos.NewBlock(x, y, z);
                     NetworkHooks.openScreen(_player, new 4(_bp), _bp);
                  }

                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "time set midnight");
                  }

                  if (world instanceof Level) {
                     _level = (Level)world;
                     if (!_level.isClientSide()) {
                        _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("thebrokenscript:glithcsound1")), SoundSource.NEUTRAL, 555.0F, 1.0F);
                     } else {
                        _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("thebrokenscript:glithcsound1")), SoundSource.NEUTRAL, 555.0F, 1.0F, false);
                     }
                  }
               }

               if (eventengine == 35.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     entityToSpawn = ((EntityType)ThebrokenscriptModEntities.NULL_INVADE_BASE.get()).create(_serverworld, BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY + 1.0D, MapVariables.get(world).baseZ), MobSpawnType.MOB_SUMMONED);
                     if (entityToSpawn != null) {
                        entityToSpawn.setYRot(world.m_213780_().m_188501_() * 360.0F);
                     }
                  }
               }

               if (eventengine == 36.0D) {
                  eventengine = 0.0D;
                  if (Math.random() < 0.7D) {
                     ((BooleanValue)world.m_6106_().m_5470_().m_46170_(GameRules.f_46140_)).m_46246_(true, world.getServer());
                  } else {
                     ((BooleanValue)world.m_6106_().m_5470_().m_46170_(GameRules.f_46140_)).m_46246_(false, world.getServer());
                  }
               }

               if (eventengine == 37.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     entityToSpawn = ((EntityType)ThebrokenscriptModEntities.BSOD.get()).create(_serverworld, BlockPos.NewBlock(x, y, z), MobSpawnType.MOB_SUMMONED);
                     if (entityToSpawn != null) {
                        entityToSpawn.setYRot(world.m_213780_().m_188501_() * 360.0F);
                     }
                  }
               }

               StructureTemplate template;
               if (eventengine == 38.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     template = _serverworld.m_215082_().m_230359_(new ResourceLocation("thebrokenscript", "obfuscatedsign"));
                     if (template != null) {
                        template.m_230328_(_serverworld, BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY + 1.0D, MapVariables.get(world).baseZ), BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY + 1.0D, MapVariables.get(world).baseZ), (new StructurePlaceSettings()).m_74379_(Rotation.m_221990_(_serverworld.f_46441_)).m_74377_(Mirror.NONE).m_74392_(false), _serverworld.f_46441_, 3);
                     }
                  }
               }

               if (eventengine == 39.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     template = _serverworld.m_215082_().m_230359_(new ResourceLocation("thebrokenscript", "giift"));
                     if (template != null) {
                        template.m_230328_(_serverworld, BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY + 1.0D, MapVariables.get(world).baseZ), BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY + 1.0D, MapVariables.get(world).baseZ), (new StructurePlaceSettings()).m_74379_(Rotation.m_221990_(_serverworld.f_46441_)).m_74377_(Mirror.NONE).m_74392_(false), _serverworld.f_46441_, 3);
                     }
                  }
               }

               if (eventengine == 40.0D) {
                  eventengine = 0.0D;
                  ThebrokenscriptMod.queueServerWork(1, () -> {
                     if (world instanceof ServerLevel) {
                        ServerLevel _level = (ServerLevel)world;
                        _level.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _level, 4, "", Component.literal(""), _level.getServer(), (Entity)null)).m_81324_(), "tellraw @a [\"\",{\"text\":\"OpenGL Error\",\"color\":\"yellow\"},{\"text\":\": 1282 (Invalid operation)\",\"color\":\"#FFFFFF\"}]");
                     }

                     ThebrokenscriptMod.queueServerWork(20, () -> {
                        if (world instanceof ServerLevel) {
                           ServerLevel _level = (ServerLevel)world;
                           _level.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _level, 4, "", Component.literal(""), _level.getServer(), (Entity)null)).m_81324_(), "tellraw @a [\"\",{\"text\":\"OpenGL Error\",\"color\":\"yellow\"},{\"text\":\": 1282 (Invalid operation)\",\"color\":\"#FFFFFF\"}]");
                        }

                        ThebrokenscriptMod.queueServerWork(20, () -> {
                           if (world instanceof ServerLevel) {
                              ServerLevel _level = (ServerLevel)world;
                              _level.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _level, 4, "", Component.literal(""), _level.getServer(), (Entity)null)).m_81324_(), "tellraw @a [\"\",{\"text\":\"OpenGL Error\",\"color\":\"yellow\"},{\"text\":\": 1282 (Invalid operation)\",\"color\":\"#FFFFFF\"}]");
                           }

                           ThebrokenscriptMod.queueServerWork(20, () -> {
                              if (world instanceof ServerLevel) {
                                 ServerLevel _level = (ServerLevel)world;
                                 _level.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _level, 4, "", Component.literal(""), _level.getServer(), (Entity)null)).m_81324_(), "tellraw @a [\"\",{\"text\":\"OpenGL Error\",\"color\":\"yellow\"},{\"text\":\": 1282 (Invalid operation)\",\"color\":\"#FFFFFF\"}]");
                              }

                              ThebrokenscriptMod.queueServerWork(100, () -> {
                                 if (world instanceof ServerLevel) {
                                    ServerLevel _levelx = (ServerLevel)world;
                                    _levelx.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _levelx, 4, "", Component.literal(""), _levelx.getServer(), (Entity)null)).m_81324_(), "tellraw @a [\"\",{\"text\":\"OpenGL Error\",\"color\":\"yellow\"},{\"text\":\": 0 (Here I am.)\",\"color\":\"#FFFFFF\"}]");
                                 }

                                 if (world instanceof Level) {
                                    Level _level = (Level)world;
                                    if (!_level.isClientSide()) {
                                       _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("ambient.cave")), SoundSource.NEUTRAL, 555.0F, 0.0F);
                                    } else {
                                       _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("ambient.cave")), SoundSource.NEUTRAL, 555.0F, 0.0F, false);
                                    }
                                 }

                              });
                           });
                        });
                     });
                  });
               }

               if (eventengine == 41.0D) {
                  eventengine = 0.0D;
                  world.m_7731_(BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), Blocks.f_50627_.m_49966_(), 3);
               }

               if (eventengine == 42.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     _serverworld.getServer().getCommands().performCommand((new CommandSourceStack(CommandSource.f_80164_, new Vec3(x, y, z), Vec2.f_82462_, _serverworld, 4, "", Component.literal(""), _serverworld.getServer(), (Entity)null)).m_81324_(), "removevhs");
                  }
               }

               if (eventengine == 43.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     entityToSpawn = ((EntityType)ThebrokenscriptModEntities.WRONG_OVERLAY.get()).create(_serverworld, BlockPos.NewBlock(x, y, z), MobSpawnType.MOB_SUMMONED);
                     if (entityToSpawn != null) {
                        entityToSpawn.setYRot(world.m_213780_().m_188501_() * 360.0F);
                     }
                  }

                  Vec3 _center = new Vec3(x, y, z);
                  List<Entity> _entfound = world.m_6443_(Entity.class, (new AABB(_center, _center)).m_82400_(500.0D), (e) -> {
                     return true;
                  }).stream().sorted(Comparator.comparingDouble((_entcnd) -> {
                     return _entcnd.m_20238_(_center);
                  })).toList();
                  Iterator var33 = _entfound.iterator();

                  while(var33.hasNext()) {
                     Entity entityiterator = (Entity)var33.next();
                     if (entityiterator instanceof Player) {
                        entityiterator.m_6021_(x, y + 50.0D, z);
                        if (entityiterator instanceof ServerPlayer) {
                           ServerPlayer _serverPlayer = (ServerPlayer)entityiterator;
                           _serverPlayer.f_8906_.m_9774_(x, y + 50.0D, z, entityiterator.m_146908_(), entityiterator.m_146909_());
                        }

                        if (entityiterator instanceof LivingEntity) {
                           LivingEntity _entity = (LivingEntity)entityiterator;
                           if (!_entity.getActiveEffects().isClientSide()) {
                              _entity.addEffect(new MobEffectInstance(MobEffects.f_19591_, 500, 1, false, false));
                           }
                        }
                     }
                  }
               }

               if (eventengine == 44.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     _serverworld.m_8767_((SimpleParticleType)ThebrokenscriptModParticleTypes.EYES.get(), x, y, z, 5, 3.0D, 3.0D, 3.0D, 0.0D);
                  }
               }

               if (eventengine == 45.0D) {
                  eventengine = 0.0D;
                  if (entity instanceof Player) {
                     _player = (Player)entity;
                     if (!_player.getActiveEffects().isClientSide()) {
                        _player.m_5661_(Component.literal("=)"), true);
                     }
                  }

                  if (world instanceof Level) {
                     _level = (Level)world;
                     if (!_level.isClientSide()) {
                        _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("thebrokenscript:textmadness1")), SoundSource.NEUTRAL, 555.0F, 0.0F);
                     } else {
                        _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("thebrokenscript:textmadness1")), SoundSource.NEUTRAL, 555.0F, 0.0F, false);
                     }
                  }

                  entity.player_rotate(Anchor.EYES, new Vec3((double)entity.getActiveEffects().m_45547_(new ClipContext(entity.m_20299_(1.0F), entity.m_20299_(1.0F).m_82549_(entity.m_20252_(1.0F).m_82490_(-5.0D)), net.minecraft.world.level.ClipContext.Block.OUTLINE, Fluid.NONE, entity)).m_82425_().m_123341_(), y, (double)entity.getActiveEffects().m_45547_(new ClipContext(entity.m_20299_(1.0F), entity.m_20299_(1.0F).m_82549_(entity.m_20252_(1.0F).m_82490_(-5.0D)), net.minecraft.world.level.ClipContext.Block.OUTLINE, Fluid.NONE, entity)).m_82425_().m_123343_()));
               }

               if (eventengine == 46.0D) {
                  eventengine = 0.0D;
                  sx = -3.0D;
                  found = false;

                  for(int index0 = 0; index0 < 6; ++index0) {
                     sy = -3.0D;

                     for(int index1 = 0; index1 < 6; ++index1) {
                        sz = -3.0D;

                        for(int index2 = 0; index2 < 6; ++index2) {
                           if (world.m_8055_(BlockPos.NewBlock(x + sx, y + sy, z + sz)).m_204336_(BlockTags.create(new ResourceLocation("minecraft:wooden_doors")))) {
                              found = true;
                           }

                           ++sz;
                        }

                        ++sy;
                     }

                     ++sx;
                  }

                  if (found) {
                     if (world instanceof Level) {
                        _level = (Level)world;
                        if (!_level.isClientSide()) {
                           _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("block.wooden_door.open")), SoundSource.NEUTRAL, 55.0F, 1.0F);
                        } else {
                           _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("block.wooden_door.open")), SoundSource.NEUTRAL, 55.0F, 1.0F, false);
                        }
                     }

                     if (entity instanceof Player) {
                        _player = (Player)entity;
                        _bp = BlockPos.NewBlock(sx, sy, sz);
                        _player.getActiveEffects().m_8055_(_bp).m_60664_(_player.getActiveEffects(), _player, InteractionHand.MAIN_HAND, BlockHitResult.m_82426_(new Vec3((double)_bp.m_123341_(), (double)_bp.m_123342_(), (double)_bp.m_123343_()), Direction.UP, _bp));
                     }
                  }
               }

               if (eventengine == 47.0D) {
                  eventengine = 0.0D;
                  if (world instanceof Level) {
                     _level = (Level)world;
                     if (!_level.isClientSide()) {
                        _level.playSound((Player)null, BlockPos.NewBlock(x, y, z), (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("thebrokenscript:moonglitch")), SoundSource.NEUTRAL, 555.0F, 1.0F);
                     } else {
                        _level.playLocalSound(x, y, z, (SoundEvent)ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("thebrokenscript:moonglitch")), SoundSource.NEUTRAL, 555.0F, 1.0F, false);
                     }
                  }

                  if (entity instanceof Player) {
                     Minecraft.m_91087_().f_91066_.m_231984_().m_231514_(2);
                  }
               }

               if (eventengine == 48.0D) {
                  eventengine = 0.0D;
                  if (entity instanceof LivingEntity) {
                     LivingEntity _entity = (LivingEntity)entity;
                     if (!_entity.getActiveEffects().isClientSide()) {
                        _entity.addEffect(new MobEffectInstance((MobEffect)ThebrokenscriptModMobEffects.WHY_CANT_YOU_LEAVE.get(), 1000, 1));
                     }
                  }
               }

               if (eventengine == 49.0D) {
                  eventengine = 0.0D;
                  if (entity instanceof ServerPlayer) {
                     _player = (ServerPlayer)entity;
                     _adv = _player.f_8924_.m_129889_().m_136041_(new ResourceLocation("thebrokenscript:can_someone_hear_me"));
                     _ap = _player.m_8960_().m_135996_(_adv);
                     if (!_ap.m_8193_()) {
                        var27 = _ap.m_8219_().iterator();

                        while(var27.hasNext()) {
                           criteria = (String)var27.next();
                           _player.m_8960_().m_135988_(_adv, criteria);
                        }
                     }
                  }
               }

               if (eventengine == 50.0D) {
                  eventengine = 0.0D;
                  if (world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     if (_serverworld.m_8802_(BlockPos.NewBlock(x, y, z)) && world instanceof ServerLevel) {
                        ServerLevel _level = (ServerLevel)world;
                        Entity entityToSpawn = ((EntityType)ThebrokenscriptModEntities.FALSE_VILLAGER.get()).create(_level, BlockPos.NewBlock(x + 40.0D, 100.0D, z), MobSpawnType.MOB_SUMMONED);
                        if (entityToSpawn != null) {
                           entityToSpawn.setYRot(world.m_213780_().m_188501_() * 360.0F);
                        }
                     }
                  }
               }

               if (eventengine == 51.0D) {
                  eventengine = 0.0D;
                  if (world.m_6042_().m_63936_(world.m_8044_()) == 1) {
                     ++MapVariables.get(world).moonphase;
                     MapVariables.get(world).syncData(world);
                  }

                  if (world.m_6042_().m_63936_(world.m_8044_()) == 8) {
                     ++MapVariables.get(world).moonphase;
                     MapVariables.get(world).syncData(world);
                  }
               }

               if (eventengine == 52.0D) {
                  eventengine = 0.0D;
                  if (MapVariables.get(world).reputation == 0.0D && world instanceof ServerLevel) {
                     _serverworld = (ServerLevel)world;
                     template = _serverworld.m_215082_().m_230359_(new ResourceLocation("thebrokenscript", "lavacast"));
                     if (template != null) {
                        template.m_230328_(_serverworld, BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), (new StructurePlaceSettings()).m_74379_(Rotation.m_221990_(_serverworld.f_46441_)).m_74377_(Mirror.values()[_serverworld.f_46441_.m_188503_(2)]).m_74392_(false), _serverworld.f_46441_, 3);
                     }
                  }
               }

               if (eventengine == 53.0D) {
                  eventengine = 0.0D;
                  if (MapVariables.get(world).reputation == 0.0D) {
                     world.m_7731_(BlockPos.NewBlock(MapVariables.get(world).baseX, MapVariables.get(world).baseY, MapVariables.get(world).baseZ), Blocks.f_49991_.m_49966_(), 3);
                  }
               }

               if (eventengine == 54.0D) {
                  eventengine = 0.0D;
                  int horizontalRadiusSquare = 9;
                  int verticalRadiusSquare = 9;
                  int yIterationsSquare = verticalRadiusSquare;

                  for(int i = -verticalRadiusSquare; i <= yIterationsSquare; ++i) {
                     for(int xi = -horizontalRadiusSquare; xi <= horizontalRadiusSquare; ++xi) {
                        for(int zi = -horizontalRadiusSquare; zi <= horizontalRadiusSquare; ++zi) {
                           world.m_7731_(BlockPos.NewBlock(x + (double)xi, y + (double)i, z + (double)zi), ((Block)ThebrokenscriptModBlocks.SHADOW_BUG.get()).m_49966_(), 3);
                        }
                     }
                  }
               }
            }

            if (world.m_8055_(BlockPos.NewBlock(x, y - 1.0D, z)).m_204336_(BlockTags.create(new ResourceLocation("thebrokenscript:houseengine"))) && Math.random() < 0.001D) {
               MapVariables.get(world).baseX = x;
               MapVariables.get(world).syncData(world);
               MapVariables.get(world).baseY = y;
               MapVariables.get(world).syncData(world);
               MapVariables.get(world).baseZ = z;
               MapVariables.get(world).syncData(world);
            }
         }

      }
   }
}
