# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.tbs_player.animation.angry_curved_idle.playing
scoreboard players set @s aj.angry_curved_idle.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:tbs_player/animations/angry_curved_idle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only