# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add aj.tbs_thumb.animation.pose.playing
scoreboard players set @s aj.pose.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:tbs_thumb/animations/pose/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only