# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.circuit.root] run return 0
function #animated_java:circuit/as_root/pre_tick
execute if entity @s[tag=aj.circuit.animation.idle.playing] run function animated_java:circuit/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.circuit.animation.idle2.playing] run function animated_java:circuit/animations/idle2/zzz/on_tick
execute if entity @s[tag=aj.circuit.animation.chase.playing] run function animated_java:circuit/animations/chase/zzz/on_tick
execute if entity @s[tag=aj.circuit.animation.chase2.playing] run function animated_java:circuit/animations/chase2/zzz/on_tick
execute if entity @s[tag=aj.circuit.animation.new.playing] run function animated_java:circuit/animations/new/zzz/on_tick
execute if entity @s[tag=aj.circuit.animation.crouchidle.playing] run function animated_java:circuit/animations/crouchidle/zzz/on_tick
execute if entity @s[tag=aj.circuit.animation.crouchwalk.playing] run function animated_java:circuit/animations/crouchwalk/zzz/on_tick
execute if entity @s[tag=aj.circuit.animation.peeking.playing] run function animated_java:circuit/animations/peeking/zzz/on_tick
execute on passengers if entity @s[tag=aj.circuit.data] run function animated_java:circuit/root/zzz/0
execute at @s on passengers run rotate @s ~ ~
function #animated_java:circuit/as_root/post_tick